#pragma once
#include "../Renderer/Colors.h"

const Color FlappyBirdArt[] = {
    TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, TRANSPARENT, BLACK, BLACK, WHITE, WHITE, WHITE, BLACK,
    WHITE, WHITE, BLACK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, BLACK, WHITE, WHITE, YELLOW, YELLOW, BLACK, WHITE, WHITE,
    WHITE, WHITE, BLACK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, BLACK, BLACK,
    BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, WHITE, WHITE, WHITE,
    BLACK, WHITE, BLACK, TRANSPARENT, TRANSPARENT, BLACK, WHITE, WHITE, WHITE,
    WHITE, BLACK, YELLOW, YELLOW, BLACK, WHITE, WHITE, WHITE, BLACK,
    WHITE, BLACK, TRANSPARENT, TRANSPARENT, BLACK, WHITE, WHITE, WHITE, WHITE,
    WHITE, BLACK, YELLOW, YELLOW, BLACK, WHITE, WHITE, WHITE, WHITE,
    BLACK, TRANSPARENT, TRANSPARENT, BLACK, YELLOW, WHITE, WHITE, WHITE, YELLOW,
    BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, TRANSPARENT, TRANSPARENT, BLACK, YELLOW, YELLOW, YELLOW, BLACK, YELLOW,
    YELLOW, YELLOW, BLACK, RED, RED, RED, RED, RED, RED,
    BLACK, TRANSPARENT, TRANSPARENT, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE,
    BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
    BLACK, RED, RED, RED, RED, RED, BLACK, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
    BLACK, BLACK, BLACK, BLACK, BLACK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, TRANSPARENT, BLACK, BLACK, BLACK, BLACK, BLACK, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT
};

// clang-format off
const Color PipeTopArt[] = {
    BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED,
    TRANSPARENT, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, BLUE_THEMED, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLUE_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, BLUE_THEMED, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLUE_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, BLUE_THEMED, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLUE_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED, TRANSPARENT, TRANSPARENT,
    TRANSPARENT, TRANSPARENT, BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED, TRANSPARENT, TRANSPARENT,

};

const Color PipeBodyArt[] = {
    TRANSPARENT, TRANSPARENT, BLUE_THEMED, GREEN_THEMED, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_LIGHT, GREEN_THEMED, GREEN_LIGHT, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_DARK, GREEN_THEMED, GREEN_THEMED, BLUE_THEMED, TRANSPARENT, TRANSPARENT,
};

const Color TestCube[] = {
    GREEN, RED, BLUE, WHITE,
    GREEN, RED, BLUE, WHITE,
    GREEN, RED, BLUE, RED,
    BLUE, GREEN, BLUE, WHITE,
    GREEN, RED, BLUE, WHITE,
};
